export { getLongestCommonSubstring } from './edit-distance/longest-common-substring'
export { getLongestCommonSubsequence, getClosestWord, getClosestWords } from './edit-distance/longest-common-subsequence'
export { getLevenshteinDistance } from './edit-distance/levenshtein'
export { getHammingDistance } from './edit-distance/hamming-distance'
export { Trie } from './data-structure/trie'
export { Rope } from './data-structure/rope'
export { contains, findAll } from './search/boyer-moore'
export { isPalindrom } from './search/palindrom'
